//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueYonder.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int ReservationId { get; set; }
        public int TravelerId { get; set; }
        public System.DateTime ReservationDate { get; set; }
        public string ConfirmationCode { get; set; }
        public int DepartFlightScheduleID { get; set; }
        public Nullable<int> ReturnFlightScheduleID { get; set; }
    
        public virtual Trip Trip { get; set; }
        public virtual Trip Trip1 { get; set; }
    }
}
